
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace NewMusicWeb
{

using System;
    using System.Collections.Generic;
    
public partial class Song
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Song()
    {

        this.Boughts = new HashSet<Bought>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public double Price { get; set; }

    public int ArtistId { get; set; }

    public Nullable<double> OverallRating { get; set; }



    public virtual Artist Artist { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Bought> Boughts { get; set; }

}

}
